config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'homes#index'
  resources 'comment_on_products' do
    post "like_comment", on: :member
    get "dislike_comment", on: :member
  end
  resources 'wishlists'
  
  resources 'orders' do
    get "cancel_payment", on: :member
  end
  #resources 'orders' do
    #member do
      #get 'show' 
    #end
  #end

  resources 'addresses'
  resources'carts' do
    collection do
      post 'apply_coupon'
      post 'create_cart_address'
      get 'destroy_coupon'
    end
  end

  resources'carts' do
    member do
      post 'add_to_cart'
      patch 'update_cart_address'
      delete 'destroy_cart_address'
    end
  end

  resources'homes' do
    get "product_details", on: :member
    post "like_product", on: :member
    get "dislike_product", on: :member
    collection do
      get 'category_search' 
      get 'product_search'
    end
  end

  resources :homes, only: [:index, :show]
  devise_for :users
  resources :authors do
    resources :books  
  end

  resources :articles do
    resources :comments
  end

  resources 'physicians' do 
    member do
      get 'see'
    end
  end

  resources 'patients' do 
    member do
      get 'see'
    end
  end

  resources 'appointments' do
    member do
      post 'upload_files'
      get 'download_prescription'
      get 'download_test_report'
    end
  end
  
  resources :students
  resources :physicians
  resources :patients
  resources :appointments
  resources :cart_items

  namespace :api, constraints: { format: :json } do
    namespace :v1, constraints: { format: :json } do
      devise_for :users, controllers: {
        sessions: 'api/v1/users/sessions',
        registrations: 'api/v1/users/registrations'
      },path: '', path_names: {
        sign_in: 'login',
        sign_out: 'logout',
        registration: 'signup'
        }
    end
  end

  namespace :api, constraints: { format: :json } do
    namespace :v1, constraints: { format: :json } do
      resources :homes, only: [:index, :show] do
        post "like_product", on: :member
        get "dislike_product", on: :member
        get 'category_search', on: :collection
        collection do
          get 'product_search'
        end
      end
      resources 'wishlists' 
      resources'carts' do
        collection do
          post 'apply_coupon'
          post 'create_cart_address'
          get 'destroy_coupon'
        end
        member do
          post 'add_to_cart'
          patch 'update_cart_address'
          delete 'destroy_cart_address'
        end
      end
      #resources 'orders'
      resources 'orders'
      resources 'cart_items'
      resources 'comment_on_products'
    end
  end
end

app/models/student.rb
class Student < ApplicationRecord
	has_many :teachers
	has_many :subjects, through: :teachers
	validate :check_length
	def check_length
		if self.name.length < 5
			errors.add(:name, "is too short so please enter a name more than 5 characters")
		end
	end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
	def index
		@students = Student.all
	end

	def show
		@student = Student.find(params[:id])
	end

	def new
		@student=Student.new
	end

	def edit
		@student = Student.find(params[:id])
	end

    def create
    	@student = Student.new(params.require(:student).permit(:name))
    	if @student.save
    		redirect_to @student
    	else
    		render 'new'
    	end
    end

	def update
		@student =Student.find(params[:id])
		if @student.update(params.require(:student).permit(:name))
			redirect_to @student
		else
			render 'edit'
		end	
	end

	def destroy
		@student = Student.find(params[:id])
		@student.destroy
		redirect_to students_path
	end
end


# http://localhost:3000/students/new

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_form.html.erb
<%= form_with scope: :student,url:students_path do|form| %>
	<% if @student.errors.any? %>
		<h2>
			<%= pluralize(@student.errors.count, "error") %> prohibited this student being saved:
		</h2>
		<ul> 
			<%= @student.errors.full_messages.each do |msg| %>
			<li>
				<%= msg %>
			</li>
			<% end %>
		</ul>
	<% end %>
	<p>
		<%= form.label :student_name %>
		<%= form.text_field :name %>
	</p>
	<p>
		<%= form.submit %>
	</p>
<% end %>

app/views/students/edit.html.erb
<h1> Edit page of student form </h1>
<%= render 'form' %>
<%= link_to "back_to_index", students_path %>

app/views/students/index.html.erb
<h1> welcome to index page </h1>
<h2> -----Listing students----- </h2>
<table>
	<tr>
		<th>Students name</th>
		<th colspan = "2"></th>
	</tr>
	<% @students.each do|student| %>
		<tr>
			<td>
				<%= student.name %>
			</td>
			<td>
				<%= link_to 'show',student_path(student) %>
			</td>
			<td>
				<%= link_to "edit",edit_student_path(student) %>
			</td>
			<td>
				<%= link_to "delete",student_path(student), method: :delete, data: { confirm:"Are you sure??" } %>
			</td>
		</tr>
	<% end %>
	<%= link_to 'new_form',new_student_path %>	
</table>

app/views/students/new.html.erb
<h1> Welcome to students page </h1>
<%= render "form" %>
<%= link_to 'back_to_index',students_path %>

app/views/students/show.html.erb
<h1>welcome to show page</h1>
<p>
	<strong> student_name: </strong> 
	<%= @student.name %> 
</p>
<%= link_to 'back_to_index', students_path %>
<%= link_to 'edit_student_form', edit_student_path(@student) %>