config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'homes#index'
  resources 'comment_on_products' do
    post "like_comment", on: :member
    get "dislike_comment", on: :member
  end
  resources 'wishlists'
  
  resources 'orders' do
    get "cancel_payment", on: :member
  end
  #resources 'orders' do
    #member do
      #get 'show' 
    #end
  #end

  resources 'addresses'
  resources'carts' do
    collection do
      post 'apply_coupon'
      post 'create_cart_address'
      get 'destroy_coupon'
    end
  end

  resources'carts' do
    member do
      post 'add_to_cart'
      patch 'update_cart_address'
      delete 'destroy_cart_address'
    end
  end

  resources'homes' do
    get "product_details", on: :member
    post "like_product", on: :member
    get "dislike_product", on: :member
    collection do
      get 'category_search' 
      get 'product_search'
    end
  end

  resources :homes, only: [:index, :show]
  devise_for :users
  resources :authors do
    resources :books  
  end

  resources :articles do
    resources :comments
  end

  resources 'physicians' do 
    member do
      get 'see'
    end
  end

  resources 'patients' do 
    member do
      get 'see'
    end
  end

  resources 'appointments' do
    member do
      post 'upload_files'
      get 'download_prescription'
      get 'download_test_report'
    end
  end
  
  resources :students
  resources :physicians
  resources :patients
  resources :appointments
  resources :cart_items

  namespace :api, constraints: { format: :json } do
    namespace :v1, constraints: { format: :json } do
      devise_for :users, controllers: {
        sessions: 'api/v1/users/sessions',
        registrations: 'api/v1/users/registrations'
      },path: '', path_names: {
        sign_in: 'login',
        sign_out: 'logout',
        registration: 'signup'
        }
    end
  end

  namespace :api, constraints: { format: :json } do
    namespace :v1, constraints: { format: :json } do
      resources :homes, only: [:index, :show] do
        post "like_product", on: :member
        get "dislike_product", on: :member
        get 'category_search', on: :collection
        collection do
          get 'product_search'
        end
      end
      resources 'wishlists' 
      resources'carts' do
        collection do
          post 'apply_coupon'
          post 'create_cart_address'
          get 'destroy_coupon'
        end
        member do
          post 'add_to_cart'
          patch 'update_cart_address'
          delete 'destroy_cart_address'
        end
      end
      #resources 'orders'
      resources 'orders'
      resources 'cart_items'
      resources 'comment_on_products'
    end
  end
end

app/models/patient.rb
class Patient < ApplicationRecord
	has_many :appointments
	has_many :physicians, :through => :appointments
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
	def index
		@patients = Patient.all
	end

	def show
	 @patient = Patient.find(params[:id])
	 end	

	def new
		@patient = Patient.new
	end

	def create
		@patient = Patient.new(params.require(:patient).permit(:name))
		if @patient.save
			redirect_to @patient
		else
			render 'new'
		end
	end

	def edit
		@patient = Patient.find(params[:id])
	end

	def update
		@patient = Patient.find(params[:id])
		if @patient.update(params.require(:patient).permit(:name))
			redirect_to @patient
		else
			render "edit"
		end
	end
	def see
		@patient = Patient.find(params[:id])
		@appointments = @patient.appointments
	end
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/patients/edit.html.erb
<h1>Edit page for patient;</h1>
<%= form_with model: @patient do |form|%>
	<p>
		<%= form.label :patient_name %>
		<%= form.text_field :name %>
	</p>
	<p>
		<%= form.submit %>
	</p>
<% end %>

app/views/patients/index.html.erb
<h1>index page:</h1>
<h2>Listing patients :</h2>
<table>
	<tr>
		<th>patient's name:</th>
		<th></th>
		<th></th>
	</tr>
	<% @patients.each do |patient| %>
		<tr>
			<td><%= patient.name %></td>
			<td><%= link_to "edit",edit_patient_path(patient) %></td> 
			<td><%= link_to "see_details",patient_path(patient) %></td> 		
		</tr>
	<% end %>
</table>

app/views/patients/new.html.erb
<%= form_with scope: :patient, url:patients_path do |form| %>
	<p>
		<%= form.label :name %>
		<%= form.text_field :name%>
	</p>
	<p>
		<%= form.submit %>
	</p>
<% end %>

app/views/patients/see.html.erb
<h1> Apppointments :</h1>
<% @appointments.each do|appointment| %>
	<%= appointment.appointment_date %> <%= appointment.physician.name %><br>
<% end %>

app/views/patients/show.html.erb
<h1>show page of Patient:</h1>
<p>
	<strong>name:</strong>
	<%= @patient.name %>
</p>
<%= link_to "edit", edit_patient_path(@patient) %><br>
<%= link_to "back_to_index",patients_path %><br>
<%= link_to "see_appointments",see_patient_path(@patient) %>