config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'homes#index'
  resources 'comment_on_products' do
    post "like_comment", on: :member
    get "dislike_comment", on: :member
  end
  resources 'wishlists'
  
  resources 'orders' do
    get "cancel_payment", on: :member
  end
  #resources 'orders' do
    #member do
      #get 'show' 
    #end
  #end

  resources 'addresses'
  resources'carts' do
    collection do
      post 'apply_coupon'
      post 'create_cart_address'
      get 'destroy_coupon'
    end
  end

  resources'carts' do
    member do
      post 'add_to_cart'
      patch 'update_cart_address'
      delete 'destroy_cart_address'
    end
  end

  resources'homes' do
    get "product_details", on: :member
    post "like_product", on: :member
    get "dislike_product", on: :member
    collection do
      get 'category_search' 
      get 'product_search'
    end
  end

  resources :homes, only: [:index, :show]
  devise_for :users
  resources :authors do
    resources :books  
  end

  resources :articles do
    resources :comments
  end

  resources 'physicians' do 
    member do
      get 'see'
    end
  end

  resources 'patients' do 
    member do
      get 'see'
    end
  end

  resources 'appointments' do
    member do
      post 'upload_files'
      get 'download_prescription'
      get 'download_test_report'
    end
  end
  
  resources :students
  resources :physicians
  resources :patients
  resources :appointments
  resources :cart_items

  namespace :api, constraints: { format: :json } do
    namespace :v1, constraints: { format: :json } do
      devise_for :users, controllers: {
        sessions: 'api/v1/users/sessions',
        registrations: 'api/v1/users/registrations'
      },path: '', path_names: {
        sign_in: 'login',
        sign_out: 'logout',
        registration: 'signup'
        }
    end
  end

  namespace :api, constraints: { format: :json } do
    namespace :v1, constraints: { format: :json } do
      resources :homes, only: [:index, :show] do
        post "like_product", on: :member
        get "dislike_product", on: :member
        get 'category_search', on: :collection
        collection do
          get 'product_search'
        end
      end
      resources 'wishlists' 
      resources'carts' do
        collection do
          post 'apply_coupon'
          post 'create_cart_address'
          get 'destroy_coupon'
        end
        member do
          post 'add_to_cart'
          patch 'update_cart_address'
          delete 'destroy_cart_address'
        end
      end
      #resources 'orders'
      resources 'orders'
      resources 'cart_items'
      resources 'comment_on_products'
    end
  end
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
	belongs_to :cart
	belongs_to :product
  after_save :total_amount
  after_destroy :total_amount_reduce
  after_save :remove_from_stock 
  after_destroy :return_to_stock


  def remove_from_stock
    product.stock_quantity -= self.quantity
    product.save
  end

  def return_to_stock
    product.stock_quantity += self.quantity
    product.save
  end

  def total_amount
    total = 0
    cart.cart_items.each do|cart_item|
      total = cart_item.price + total
    end
    cart.update(total: total)
    if cart.coupon_id.present?
      coupon_id = cart.coupon_id
      coupon = Coupon.find(coupon_id)
      cart.check_coupon(coupon)
    end
  end

  def total_amount_reduce
    total = cart.total
    total = total - self.price
    cart.update(total: total)
    if cart.coupon_id.present?
      coupon_id = cart.coupon_id
      coupon = Coupon.find(coupon_id)
      if cart.total <= coupon.min_cart_value
        coupon_id = nil
        discount = 0
        cart.update(coupon_id: coupon_id, discount: discount)
      else
      cart.check_coupon(coupon)
      end
    end
  end
end

app/controllers/api/v1/cart_items_controller.rb
module Api
    module V1		
		class CartItemsController < ApiController
			#before_action :authenticate_user!
			def index
				#byebug
				@cart = current_user.cart
				#byebug
				cart_id = @cart.id
				@cart_items = CartItem.where(cart_id: cart_id)
				if current_user.cart.present?
					cart = current_user.cart
					@address = cart.address
				end
				render json: @cart_items
			end

			def destroy
				cart = current_user.cart
				@cart_item =CartItem.find(params[:id])
				@cart_item.destroy
			    render json: {meta:{message: "successfully remove from cart"}}

			end
		end
	end
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
	def index
		#byebug
		@cart = current_user.cart
		#byebug
		cart_id = @cart.id
		@cart_items = CartItem.where(cart_id: cart_id)
		if current_user.cart.present?
			cart = current_user.cart
			@address = cart.address
		end
	end

	def destroy
		cart = current_user.cart
		@cart_item =CartItem.find(params[:id])
		@cart_item.destroy
		redirect_to cart_items_path

	end
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/views/cart_items/index.html.erb
<table>
  <tr>
    <th>name</th>
    <th>price</th>
    <th>quantity</th>
    <th>images</th>
    <th></th>
  </tr>
<% if current_user.cart.present? %>
  <% if current_user.cart.cart_items.present? %>
    <% @cart_items.each do |cart_item| %>
      <tr>
        <td><%= cart_item.name %></td>
        <td><%= cart_item.price %></td>
        <td><%= cart_item.quantity %></td>
        <td><%= image_tag cart_item.product.image, style: "width:100px;height:100px" %><br></td>
        <td><%= link_to "remove_item",cart_item_path(cart_item),method: :delete, data: { confirm: 'Are You sure?' } %></td>
      </tr>
    <% end %>
  <% end %>
<% end %>

</table>
<% if current_user.cart.present? %>
  <h3>total_amount: <%= current_user.cart.total %></h3>
  <% if current_user.cart.discount.present? %>
     <h3>discount: <%= current_user.cart.discount %></h3>
    <% if current_user.cart.total >= 0 %>
      <h3>total_amount_with_discount: <%= current_user.cart.total - current_user.cart.discount %><br>
    <% else %>
      <h3><% current_user.cart.total %></h3>
    <% end %>
  <% end %><br>
  <% if current_user.cart.address.present? %>
    <h1> delievery address:</h1>
    <p>
      <strong>name:</strong>
      <%= @address.name %>
    </p>
 
    <p>
      <strong>contact_number:</strong>
      <%= @address.contact_number %>
    </p>

    <p>
      <strong>email_id:</strong>
      <%= @address.email_id %>
    </p>

    <p>
      <strong>address:</strong>
      <%= @address.address %>
    </p>

    <%= button_to "edit_address",edit_address_path(@address),method: :get %><br>
    <%= button_to "remove_address",destroy_cart_address_cart_path(@address),method: :delete %>
    <% unless current_user.order.present? %>
      <%= button_to "place_order",orders_path,method: :post %>
    <% end %>
  <% end %><br>
  <% if current_user.cart.cart_items.present? %>
    <% unless current_user.cart.coupon_id.present? %>
      <%= form_tag apply_coupon_carts_path, method: :post do %>
        <h3>
          <%= label_tag :coupon_code %>
          <%= text_field_tag :code %>
          <%= submit_tag "apply_coupon" %>   
        </h3>
      <% end %>
    <% end %>
  <% end %>
  <% if current_user.cart.cart_items.present? %>
    <% unless current_user.cart.address.present? %>
      <%= button_to "add_delievery_address",new_address_path,method: :get %><br>
    <% end %>
  <% end %>
  <% if current_user.cart.coupon_id.present? %>
    <%= button_to "remove_coupon",destroy_coupon_carts_path,method: :get %>
  <% end %>
  <% if current_user.order.present? %>
    <%= button_to "see_orders",orders_path,method: :get %>
  <% end %>
<% end %>
<%= button_to "search_new_products",product_search_homes_path,method: :get %><br>